name: yourlife.church
favicon: null
layout_spectrum: 0.8484293194487691
typography_spectrum: 0.06476038903929293
title: yourlife.church
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070708'
    - '#ffffff'
    - '#3b3c3b'
    - '#6d6d6d'
    - '#adadad'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
